[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/equipe/equipe-editoriale/"
to = "/asso/equipe/"

[[redirects]]
from = "/agenda/archives/"
to = "/festival/"

[[redirects]]
from = "/festival/archives/"
to = "/festival/"

[[redirects]]
from = "/festival/2023-03-03-les-corps-lesbiens-1/"
to = "/festival/2023/les-corps-lesbiens-1/"

[[redirects]]
from = "/asso/equipe-editoriale/"
to = "/asso/equipe/"

[[redirects]]
from = "/organisations/"
to = "/contact/"

[[redirects]]
from = "/contacy/"
to = "/contact/"

[[redirects]]
from = "/equipe/"
to = "/asso/"

[[redirects]]
from = "/agenda/"
to = "/festival/"

